### ISSUE TITLE
Support linting out of the box

### ISSUE THREAD

**Issue by slifty** [PermanentOrg/devenv#38]
Running our PHP linter in the devenv requires a one-time manual invocation of `php library/bin/composer.phar install --prefer-dist --working-dir=tools/phplint`

I believe this should be easy enough to automate.

@Fenn-CS correctly points out that in an ideal world we wouldn't have random `composer.json`s lurking in the code base.  I agree with the spirit but also think that would be a heavier lift and so for now we should just support out-of-the-box-linting with the current state.

**Comment by jasonaowen** [comment]
> in an ideal world we wouldn't have random `composer.phar`s lurking in the code base

Having tools live in a separate directory with individually-managed dependencies was an intentional decision to work around a limitation in composer. Because it does not support having multiple versions of dependencies installed at the same time, installing dev tools either means limiting the dev tool versions to the old dependencies we have in back-end, or else it means making changes to our production dependencies in order to allow dev tools. Neither are are good practice.

Here's what I wrote in the commit messages introducing those tools:

> Install [tool] in a new `tools/` directory, with a separate composer environment. This allows us to avoid deploying it or any of its dependencies to production, as well as prevents any version conflicts between its dependencies and our dependencies.

In an ideal world, composer would allow us to manage such dependency conflicts sensibility, but this is the suggested approach for solving this problem. From the [PHP-CS-Fixer installation instructions](https://github.com/FriendsOfPhp/PHP-CS-Fixer#documentation):

> The recommended way to install PHP CS Fixer is to use [Composer](https://getcomposer.org/download/) in a dedicated `composer.json` file in your project, for example in the `tools/php-cs-fixer` directory

**Comment by slifty** [comment]
Whoops typo (fixing to `.json`).

Ahhh composer. *sigh* -- the eternal destroyer of ideal worlds.

Yep that makes lots of sense.
